name: Email Step Workflow

on:
  push:
    branches:
      - main  # Or your default branch name

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 25ds3000025@ds.study.iitm.ac.in
        run: echo "Hello, world!"
